
const GENERACION = {
  FETCH: 'GENERACION_FETCH',
  FETCH_ERROR: 'GENERACION_FETCH_ERROR',
  FETCH_SUCCESS: 'GENERACION_FETCH_SUCCESS'
};

const DRAGON = {
  FETCH: 'DRAGON_FETCH',
  FETCH_ERROR: 'DRAGON_FETCH_ERROR',
  FETCH_SUCCESS: 'DRAGON_FETCH_SUCCESS'
};

const CUENTA = {
  FETCH: 'CUENTA_FETCH',
  FETCH_ERROR: 'CUENTA_FETCH_ERROR',
  FETCH_SUCCESS: 'CUENTA_FETCH_SUCCESS',
  FETCH_LOGOUT_SUCCESS: 'CUENTA_FETCH_LOGOUT_SUCCESS',
  FETCH_AUTHENTICATED_SUCCESS: 'CUENTA_FETCH_AUTHENTICATED_SUCCESS'
};

const CUENTA_DRAGONES = {
  FETCH: 'CUENTA_DRAGONES_FETCH',
  FETCH_ERROR: 'CUENTA_DRAGONES_FETCH_ERROR',
  FETCH_SUCCESS: 'CUENTA_DRAGONES_FETCH_SUCCESS'
};

const CUENTA_INFO = {
  FETCH: 'CUENTA_INFO_FETCH',
  FETCH_ERROR: 'CUENTA_INFO_FETCH_ERROR',
  FETCH_SUCCESS: 'CUENTA_INFO_FETCH_SUCCESS'
};

const DRAGONES_PUBLICOS = {
  FETCH: 'DRAGONES_PUBLICOS_FETCH',
  FETCH_ERROR: 'DRAGONES_PUBLICOS_FETCH_ERROR',
  FETCH_SUCCESS: 'DRAGONES_PUBLICOS_FETCH_SUCCESS'
};

export {
  GENERACION,
  DRAGON,
  CUENTA,
  CUENTA_DRAGONES,
  CUENTA_INFO,
  DRAGONES_PUBLICOS
};